# Generated by Django 3.1 on 2020-08-26 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
        migrations.AlterField(
            model_name='news',
            name='creation_date',
            field=models.DateField(help_text='Дата создания'),
        ),
        migrations.AlterField(
            model_name='news',
            name='heading',
            field=models.CharField(help_text='Заголовок новости - 40 символов', max_length=40),
        ),
        migrations.AlterField(
            model_name='news',
            name='update_date',
            field=models.DateField(help_text='Дата обновления'),
        ),
    ]
