# Generated by Django 3.1 on 2020-08-26 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_auto_20200827_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='heading',
            field=models.CharField(help_text='Заголовок новости - 40 символов', max_length=80),
        ),
    ]
