# Generated by Django 3.1 on 2020-08-26 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0004_auto_20200827_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='heading',
            field=models.CharField(help_text='Заголовок новости - 80 символов', max_length=80),
        ),
    ]
