# Generated by Django 3.1 on 2020-08-31 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0005_auto_20200827_0441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='heading',
            new_name='title',
        ),
    ]
