# Generated by Django 3.1 on 2020-10-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Название бренда')),
                ('guid', models.CharField(max_length=100, verbose_name='guid')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название категории')),
                ('guid', models.CharField(max_length=100, verbose_name='guid')),
                ('level', models.PositiveSmallIntegerField(default=0, verbose_name='Уровень вложенности')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название коллекции')),
                ('guid', models.CharField(max_length=100, verbose_name='guid')),
            ],
            options={
                'verbose_name': 'Коллекция',
                'verbose_name_plural': 'Коллекции',
            },
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название дизайна')),
                ('guid', models.CharField(max_length=100, verbose_name='guid')),
            ],
            options={
                'verbose_name': 'Дизайн',
                'verbose_name_plural': 'Дизайны',
            },
        ),
        migrations.CreateModel(
            name='GenderType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Принадлежность')),
                ('guid', models.CharField(max_length=100, verbose_name='guid')),
            ],
            options={
                'verbose_name': 'Половая принадлежность',
                'verbose_name_plural': 'Половая принадлежность',
            },
        ),
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название производителя')),
                ('guid', models.CharField(max_length=100, verbose_name='guid')),
            ],
            options={
                'verbose_name': 'Хэш-Тег',
                'verbose_name_plural': 'Хэш-Теги',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagename', models.CharField(max_length=200, verbose_name='Название картинки')),
                ('guid', models.CharField(max_length=100, verbose_name='guid')),
                ('imagesize', models.PositiveIntegerField(verbose_name='Размер картинки')),
                ('imageext', models.CharField(max_length=20, verbose_name='Расширение картинки')),
                ('imagemask', models.ImageField(blank=True, upload_to='images/%Y/%m/', verbose_name='Путь к картинке')),
                ('imagetype', models.PositiveSmallIntegerField(default=0, verbose_name='Тип картинки')),
                ('imagesubtype', models.PositiveSmallIntegerField(null=True, verbose_name='Подтип картинки')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название Производителя')),
                ('guid', models.CharField(max_length=100, verbose_name='guid')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название размера')),
                ('guid', models.CharField(max_length=100, verbose_name='guid')),
            ],
            options={
                'verbose_name': 'Размер',
                'verbose_name_plural': 'Размеры',
            },
        ),
        migrations.CreateModel(
            name='TypeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название типа')),
                ('guid', models.CharField(max_length=100, verbose_name='guid')),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Типы',
            },
        ),
    ]
