# Generated by Django 3.1 on 2020-10-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productoffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoffer',
            name='images',
            field=models.ManyToManyField(related_name='image_set', to='products.Image', verbose_name='Фотографии'),
        ),
    ]
