# Generated by Django 3.1 on 2020-10-14 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20201014_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название продукта')),
                ('guid', models.CharField(max_length=100, verbose_name='guid')),
                ('isshoes', models.BooleanField(verbose_name='Обувь?')),
                ('articleh', models.CharField(max_length=40, verbose_name='Артикул')),
                ('price', models.FloatField(blank=True, default=0.0, verbose_name='Цена')),
                ('old_price', models.FloatField(blank=True, default=0.0, verbose_name='Старая цена')),
                ('count', models.PositiveSmallIntegerField(default=0, verbose_name='Количество')),
                ('images', models.ManyToManyField(related_name='images', to='products.Image', verbose_name='Фотографии')),
                ('product_offer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='products.productoffer', verbose_name='Торговое предложение')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.size', verbose_name='Размер')),
            ],
        ),
    ]
