# Generated by Django 3.1 on 2020-10-14 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20201014_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='NomenSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namesetprodtype', models.SmallIntegerField(unique=True, verbose_name='Положение в наборе')),
                ('guid', models.CharField(max_length=100, verbose_name='guid')),
            ],
            options={
                'verbose_name': 'Список товаров',
                'verbose_name_plural': 'Списки товаров',
            },
        ),
        migrations.AlterModelOptions(
            name='productoffer',
            options={'verbose_name': 'Положение продукта', 'verbose_name_plural': 'Положения продукта'},
        ),
        migrations.CreateModel(
            name='ProductOfferSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Торговое предложение')),
                ('guid', models.CharField(max_length=100, verbose_name='guid')),
                ('article', models.CharField(max_length=30, verbose_name='Артикул')),
                ('description', models.TextField(verbose_name='Описание')),
                ('smallsize', models.BooleanField(verbose_name='Маленький ли размер?')),
                ('length', models.PositiveIntegerField(verbose_name='Длина')),
                ('width', models.PositiveIntegerField(verbose_name='Ширина')),
                ('height', models.PositiveIntegerField(verbose_name='Высота')),
                ('weight', models.FloatField(verbose_name='Вес')),
                ('isshoes', models.BooleanField(verbose_name='Обувь?')),
                ('mainprice', models.FloatField(blank=True, default=0.0, verbose_name='Цена')),
                ('subprodtype', models.PositiveSmallIntegerField(default=0, verbose_name='Подтип')),
                ('is_new', models.BooleanField(verbose_name='Новинка?')),
                ('is_hit', models.BooleanField(verbose_name='Хит продаж?')),
                ('is_set', models.BooleanField(verbose_name='Набор?')),
                ('is_sale', models.BooleanField(verbose_name='Распродажа?')),
                ('addprods', models.ManyToManyField(related_name='_productofferset_addprods_+', to='products.ProductOfferSet', verbose_name='Похожие')),
                ('analogs', models.ManyToManyField(related_name='_productofferset_analogs_+', to='products.ProductOfferSet', verbose_name='Аналоги')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.brands', verbose_name='Бренд')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Категория')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.collection', verbose_name='Коллекция')),
                ('gender_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.gendertype', verbose_name='Половая принадлежность')),
                ('images', models.ManyToManyField(related_name='images_in_productset', to='products.Image', verbose_name='Фотографии')),
                ('is_mainphoto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.image', verbose_name='Фотография')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.manufacturer', verbose_name='Производитель')),
                ('nomen_sets', models.ManyToManyField(to='products.NomenSet', verbose_name='Положение товаров в наборе')),
            ],
        ),
    ]
