# Generated by Django 3.1 on 2020-10-14 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20201014_1818'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productofferset',
            options={'verbose_name': 'Набор', 'verbose_name_plural': 'Наборы'},
        ),
    ]
