# Generated by Django 3.1 on 2020-10-14 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20201014_1819'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nomenset',
            options={'verbose_name': 'Положение товара в наборе', 'verbose_name_plural': 'Положения товаров в наборе'},
        ),
        migrations.AlterModelOptions(
            name='productoffer',
            options={'verbose_name': 'Предложение', 'verbose_name_plural': 'Предложения'},
        ),
    ]
