# Generated by Django 3.1 on 2020-10-15 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20201014_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Characteristics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Характеристики товара')),
                ('guid', models.CharField(max_length=100, verbose_name='guid')),
                ('article', models.CharField(max_length=30, verbose_name='Артикул')),
                ('description', models.TextField(verbose_name='Описание')),
                ('smallsize', models.BooleanField(verbose_name='Маленький ли размер?')),
                ('length', models.PositiveIntegerField(verbose_name='Длина')),
                ('width', models.PositiveIntegerField(verbose_name='Ширина')),
                ('height', models.PositiveIntegerField(verbose_name='Высота')),
                ('weight', models.FloatField(verbose_name='Вес')),
                ('isshoes', models.BooleanField(verbose_name='Обувь?')),
                ('artexh', models.CharField(max_length=256, verbose_name='Доп инфа + id цвета')),
                ('mainprice', models.FloatField(blank=True, default=0.0, verbose_name='Цена')),
                ('mainold_price', models.FloatField(blank=True, default=0.0, verbose_name='Старая цена')),
                ('is_new', models.BooleanField(verbose_name='Новинка?')),
                ('is_hit', models.BooleanField(verbose_name='Хит продаж?')),
                ('is_set', models.BooleanField(verbose_name='Набор?')),
                ('is_sale', models.BooleanField(verbose_name='Распродажа?')),
                ('maintenance', models.CharField(max_length=256, verbose_name='Уход за товаром')),
                ('count', models.PositiveSmallIntegerField(default=0, verbose_name='Количество')),
                ('addprods', models.ManyToManyField(related_name='_characteristics_addprods_+', to='products.Characteristics', verbose_name='Похожие')),
                ('analogs', models.ManyToManyField(related_name='_characteristics_analogs_+', to='products.Characteristics', verbose_name='Аналоги')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.brands', verbose_name='Бренд')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Категория')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.collection', verbose_name='Коллекция')),
                ('designs', models.ManyToManyField(to='products.Design', verbose_name='Дизайн')),
                ('gender_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.gendertype', verbose_name='Половая принадлежность')),
                ('images', models.ManyToManyField(related_name='image_set', to='products.Image', verbose_name='Фотографии')),
                ('is_mainphoto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.image', verbose_name='Фотография')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.manufacturer', verbose_name='Производитель')),
                ('prodtypes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.typemodel', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Предложение',
                'verbose_name_plural': 'Предложения',
            },
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Торговое предложение')),
                ('guid', models.CharField(max_length=100, verbose_name='guid')),
                ('article', models.CharField(max_length=30, verbose_name='Артикул')),
                ('description', models.TextField(verbose_name='Описание')),
                ('smallsize', models.BooleanField(verbose_name='Маленький ли размер?')),
                ('length', models.PositiveIntegerField(verbose_name='Длина')),
                ('width', models.PositiveIntegerField(verbose_name='Ширина')),
                ('height', models.PositiveIntegerField(verbose_name='Высота')),
                ('weight', models.FloatField(verbose_name='Вес')),
                ('isshoes', models.BooleanField(verbose_name='Обувь?')),
                ('mainprice', models.FloatField(blank=True, default=0.0, verbose_name='Цена')),
                ('subprodtype', models.PositiveSmallIntegerField(default=0, verbose_name='Подтип')),
                ('is_new', models.BooleanField(verbose_name='Новинка?')),
                ('is_hit', models.BooleanField(verbose_name='Хит продаж?')),
                ('is_set', models.BooleanField(verbose_name='Набор?')),
                ('is_sale', models.BooleanField(verbose_name='Распродажа?')),
                ('addprods', models.ManyToManyField(related_name='_set_addprods_+', to='products.Set', verbose_name='Похожие')),
                ('analogs', models.ManyToManyField(related_name='_set_analogs_+', to='products.Set', verbose_name='Аналоги')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.brands', verbose_name='Бренд')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Категория')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.collection', verbose_name='Коллекция')),
                ('gender_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.gendertype', verbose_name='Половая принадлежность')),
                ('images', models.ManyToManyField(related_name='images_in_productset', to='products.Image', verbose_name='Фотографии')),
                ('is_mainphoto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.image', verbose_name='Фотография')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.manufacturer', verbose_name='Производитель')),
                ('nomen_sets', models.ManyToManyField(to='products.NomenSet', verbose_name='Положение товаров в наборе')),
            ],
            options={
                'verbose_name': 'Набор',
                'verbose_name_plural': 'Наборы',
            },
        ),
        migrations.RemoveField(
            model_name='productofferset',
            name='addprods',
        ),
        migrations.RemoveField(
            model_name='productofferset',
            name='analogs',
        ),
        migrations.RemoveField(
            model_name='productofferset',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='productofferset',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productofferset',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='productofferset',
            name='gender_type',
        ),
        migrations.RemoveField(
            model_name='productofferset',
            name='images',
        ),
        migrations.RemoveField(
            model_name='productofferset',
            name='is_mainphoto',
        ),
        migrations.RemoveField(
            model_name='productofferset',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='productofferset',
            name='nomen_sets',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_offer',
        ),
        migrations.DeleteModel(
            name='ProductOffer',
        ),
        migrations.DeleteModel(
            name='ProductOfferSet',
        ),
        migrations.AddField(
            model_name='product',
            name='characteristics',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='products.characteristics', verbose_name='Характеристики товара'),
        ),
    ]
