# Generated by Django 3.1 on 2020-10-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20201015_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameid', models.PositiveIntegerField(unique=True, verbose_name='id имени')),
                ('name', models.CharField(max_length=200, verbose_name='Название цвета')),
                ('guid', models.CharField(max_length=100, verbose_name='guid')),
                ('nametwo', models.CharField(max_length=200, null=True, verbose_name='Дополнительное название')),
                ('hexcode', models.CharField(max_length=100, null=True, verbose_name='Цвет в числовом представлении')),
                ('images', models.ManyToManyField(related_name='color_images', to='products.Image', verbose_name='Фотографии')),
            ],
            options={
                'verbose_name': 'Дизайн',
                'verbose_name_plural': 'Дизайны',
            },
        ),
    ]
