# Generated by Django 3.1 on 2020-10-15 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20201016_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='typemodel',
            name='nametypeid',
            field=models.PositiveIntegerField(default=0, verbose_name='id типа'),
        ),
    ]
