# Generated by Django 3.1 on 2020-10-15 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_typemodel_nametypeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typemodel',
            name='nametypeid',
            field=models.PositiveIntegerField(verbose_name='id типа'),
        ),
    ]
