# Generated by Django 3.1 on 2020-10-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_characteristics_composition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristics',
            name='composition',
            field=models.TextField(null=True, verbose_name='Сравнение'),
        ),
    ]
