# Generated by Django 3.1 on 2020-10-16 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20201016_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristics',
            name='prodtypes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.typemodel', verbose_name='Тип'),
        ),
    ]
