# Generated by Django 3.1 on 2020-10-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_auto_20201016_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristics',
            name='article',
            field=models.TextField(verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='maintenance',
            field=models.TextField(verbose_name='Уход за товаром'),
        ),
    ]
