# Generated by Django 3.1 on 2020-10-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_auto_20201016_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characteristics',
            name='prodtypes',
        ),
        migrations.AddField(
            model_name='characteristics',
            name='prodtypes',
            field=models.ManyToManyField(to='products.TypeModel', verbose_name='Тип'),
        ),
    ]
