# Generated by Django 3.1 on 2020-10-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_auto_20201016_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristics',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='maintenance',
            field=models.TextField(null=True, verbose_name='Уход за товаром'),
        ),
    ]
