# Generated by Django 3.1 on 2020-10-16 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_auto_20201016_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristics',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.brands', verbose_name='Бренд'),
        ),
    ]
