# Generated by Django 3.1 on 2020-10-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_auto_20201016_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='guid',
            field=models.CharField(max_length=200, verbose_name='guid'),
        ),
    ]
