# Generated by Django 3.1 on 2020-10-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_auto_20201016_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='guid',
            field=models.TextField(verbose_name='guid'),
        ),
        migrations.AlterField(
            model_name='image',
            name='imagename',
            field=models.TextField(verbose_name='Название картинки'),
        ),
    ]
