# Generated by Django 3.1 on 2020-10-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_auto_20201016_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='imageext',
            field=models.TextField(verbose_name='Расширение картинки'),
        ),
    ]
