# Generated by Django 3.1 on 2020-10-16 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_auto_20201016_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristics',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.collection', verbose_name='Коллекция'),
        ),
    ]
