# Generated by Django 3.1 on 2020-10-19 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_auto_20201019_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='articleh',
            field=models.CharField(max_length=40, null=True, verbose_name='Артикул'),
        ),
    ]
