# Generated by Django 3.1 on 2020-10-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_auto_20201019_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='composition',
            field=models.TextField(null=True, verbose_name='Сравнение'),
        ),
    ]
