# Generated by Django 3.1 on 2020-10-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0041_set_maintenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='isshoes',
            field=models.BooleanField(null=True, verbose_name='Обувь?'),
        ),
    ]
