# Generated by Django 3.1 on 2020-10-19 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0044_auto_20201019_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
    ]
