# Generated by Django 3.1 on 2020-10-19 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0045_auto_20201019_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='gender_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.gendertype', verbose_name='Половая принадлежность'),
        ),
    ]
