# Generated by Django 3.1 on 2020-10-20 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0048_auto_20201019_1420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nomenset',
            old_name='namesetprodtype',
            new_name='nomensetprodtype',
        ),
    ]
