# Generated by Django 3.1 on 2020-10-20 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0049_auto_20201020_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nomenset',
            old_name='nomensetprodtype',
            new_name='nomensetpodtype',
        ),
    ]
