# Generated by Django 3.1 on 2020-10-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0050_auto_20201020_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomenset',
            name='nomensetpodtype',
            field=models.SmallIntegerField(verbose_name='Положение в наборе'),
        ),
    ]
