# Generated by Django 3.1 on 2020-10-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0051_auto_20201020_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Название бренда'),
        ),
    ]
