# Generated by Django 3.1 on 2020-10-26 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0054_auto_20201023_1152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='characteristics',
            old_name='gender_type',
            new_name='gendertype',
        ),
        migrations.RenameField(
            model_name='set',
            old_name='gender_type',
            new_name='gendertype',
        ),
    ]
