# Generated by Django 3.1 on 2020-10-30 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0056_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='code',
            field=models.IntegerField(verbose_name='Код города'),
        ),
        migrations.AlterField(
            model_name='city',
            name='sub_region',
            field=models.IntegerField(verbose_name='Код региона'),
        ),
    ]
