# Generated by Django 3.1 on 2020-10-30 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0057_auto_20201030_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=100, verbose_name='Регион')),
                ('region_code', models.IntegerField(verbose_name='Код региона')),
            ],
            options={
                'verbose_name': 'Область',
                'verbose_name_plural': 'Области',
            },
        ),
        migrations.RemoveField(
            model_name='city',
            name='region_code',
        ),
        migrations.RemoveField(
            model_name='city',
            name='sub_region',
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.region', verbose_name='Регион'),
        ),
    ]
