# Generated by Django 3.1 on 2020-10-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0058_auto_20201030_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='code',
            field=models.IntegerField(null=True, verbose_name='Код города'),
        ),
    ]
